import { BodyStructureType } from '../types';

export interface RigProfile {
  rigAsset: string | null;
  animations: Record<string, string>;
  animationSpeeds?: Record<string, number>;
}

export const CREATURE_RIG_PROFILES: Record<BodyStructureType, RigProfile> = {
  humanoid: {
    rigAsset: 'proc://rig/humanoid',
    animations: {
      stand_idle: 'proc://anim/humanoid/stand_idle',
      airborne: 'proc://anim/humanoid/airborne',
      stand_walk: 'proc://anim/humanoid/stand_walk',
      stand_jog: 'proc://anim/humanoid/stand_jog',
      stand_sprint: 'proc://anim/humanoid/stand_sprint',
      crouch_idle: 'proc://anim/humanoid/crouch_idle',
      crouch_walk: 'proc://anim/humanoid/crouch_walk',
      crouch_jog: 'proc://anim/humanoid/crouch_jog',
      crouch_sprint: 'proc://anim/humanoid/crouch_sprint',
      prone_idle: 'proc://anim/humanoid/prone_idle',
      prone_crawl: 'proc://anim/humanoid/prone_crawl',
      stand_to_crouch: 'proc://anim/humanoid/stand_to_crouch',
      crouch_to_stand: 'proc://anim/humanoid/crouch_to_stand',
      stand_to_prone: 'proc://anim/humanoid/stand_to_prone',
      prone_to_stand: 'proc://anim/humanoid/prone_to_stand',
      crouch_to_prone: 'proc://anim/humanoid/crouch_to_prone',
      prone_to_crouch: 'proc://anim/humanoid/prone_to_crouch',
      swim_idle: 'proc://anim/humanoid/swim_idle',
      swim_walk: 'proc://anim/humanoid/swim_walk',
      swim_jog: 'proc://anim/humanoid/swim_jog',
      swim_sprint: 'proc://anim/humanoid/swim_sprint',
      attack: 'proc://anim/humanoid/attack_left_hand',
      attack_left_hand: 'proc://anim/humanoid/attack_left_hand',
      attack_right_hand: 'proc://anim/humanoid/attack_right_hand',
      pickup: 'proc://anim/humanoid/pickup_left_hand',
      pickup_left_hand: 'proc://anim/humanoid/pickup_left_hand',
      pickup_right_hand: 'proc://anim/humanoid/pickup_right_hand',
      drop_item: 'proc://anim/humanoid/drop_item_left_hand',
      drop_item_left_hand: 'proc://anim/humanoid/drop_item_left_hand',
      drop_item_right_hand: 'proc://anim/humanoid/drop_item_right_hand',
      throw_item: 'proc://anim/humanoid/throw_item_left_hand',
      throw_item_left_hand: 'proc://anim/humanoid/throw_item_left_hand',
      throw_item_right_hand: 'proc://anim/humanoid/throw_item_right_hand',
      put_on: 'proc://anim/humanoid/put_on',
      take_off: 'proc://anim/humanoid/take_off',
      throw: 'proc://anim/humanoid/drop_item_left_hand',
      retrieve_inv: 'proc://anim/humanoid/retrieve_inv',
      store_inv: 'proc://anim/humanoid/store_inv',
      dead: 'proc://anim/humanoid/dead',
      fall_back: 'proc://anim/humanoid/fall_back',
    },
    animationSpeeds: {
      attack: 1.5,
      attack_left_hand: 1.5,
      attack_right_hand: 1.5,
      pickup: 0.9,
      pickup_left_hand: 0.9,
      pickup_right_hand: 0.9,
      drop_item: 1.0,
      drop_item_left_hand: 1.0,
      drop_item_right_hand: 1.0,
      throw_item: 1.0,
      throw_item_left_hand: 1.0,
      throw_item_right_hand: 1.0,
      throw: 1.0,
      stand_sprint: 1.0,
      crouch_sprint: 1.0,
      swim_sprint: 1.3,
    },
  },
  quadruped: {
    rigAsset: 'proc://rig/quadruped',
    animations: {
      stand_idle: 'proc://anim/quadruped/stand_idle',
      airborne: 'proc://anim/quadruped/airborne',
      stand_walk: 'proc://anim/quadruped/stand_walk',
      stand_jog: 'proc://anim/quadruped/stand_jog',
      stand_sprint: 'proc://anim/quadruped/stand_sprint',
      crouch_idle: 'proc://anim/quadruped/crouch_idle',
      crouch_walk: 'proc://anim/quadruped/crouch_walk',
      crouch_jog: 'proc://anim/quadruped/crouch_jog',
      crouch_sprint: 'proc://anim/quadruped/crouch_sprint',
      prone_idle: 'proc://anim/quadruped/prone_idle',
      prone_crawl: 'proc://anim/quadruped/prone_crawl',
      stand_to_prone: 'proc://anim/quadruped/stand_to_prone',
      prone_to_stand: 'proc://anim/quadruped/prone_to_stand',
      swim_idle: 'proc://anim/quadruped/swim_idle',
      swim_walk: 'proc://anim/quadruped/swim_walk',
      swim_jog: 'proc://anim/quadruped/swim_jog',
      swim_sprint: 'proc://anim/quadruped/swim_sprint',
      attack: 'proc://anim/quadruped/attack',
      pickup: 'proc://anim/quadruped/pickup_jaws',
      pickup_jaws: 'proc://anim/quadruped/pickup_jaws',
      drop_item: 'proc://anim/quadruped/drop_item_jaws',
      drop_item_jaws: 'proc://anim/quadruped/drop_item_jaws',
      throw: 'proc://anim/quadruped/throw_item_jaws',
      throw_item: 'proc://anim/quadruped/throw_item_jaws',
      throw_item_jaws: 'proc://anim/quadruped/throw_item_jaws',
      dead: 'proc://anim/quadruped/dead',
    },
    animationSpeeds: {
      stand_sprint: 1.4,
      crouch_sprint: 1.2,
      swim_sprint: 1.3,
      pickup: 1.0,
      pickup_jaws: 1.0,
      drop_item: 1.0,
      drop_item_jaws: 1.0,
      throw: 1.0,
      throw_item: 1.0,
      throw_item_jaws: 1.0,
    },
  },
  arachnid: {
    rigAsset: null,
    animations: {},
  },
};
