name: Build and Deploy to Itch.io

on:
  push:
    branches:
      - main # Название вашей основной ветки (main или master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # 3. Ставим зависимости и собираем проект через bun
      - name: Install dependencies & Build
        run: |
          bun install --frozen-lockfile
          bun run build

      # 4. Выгружаем собранную папку dist на itch.io
      - name: Deploy to Itch.io
        uses: [yeslayla/butler-publish-itchio-action](https://github.com/marketplace/actions/butler-push)@v1.2.0
        with:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html5
          ITCH_GAME: dungeoned
          ITCH_USER: grimthinker
          PACKAGE: dist
