name: Build and Deploy to Itch.io

on:
  push:
    branches:
      - main # Название вашей основной ветки (main или master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # 3. Ставим зависимости и собираем проект через bun
      - name: Install dependencies & Build
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Setup Butler
        uses: remarkablegames/setup-butler@v2

      - name: Upload Build to itch.io
        run: butler push dist grimthinker/dungeoned:html5
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
